### ISSUE TITLE
Markdown file below sample code parsed incorrectly

### ISSUE THREAD

**Issue by Hellboy1008** [exlskills/eocsutil#4]
![code markdown 1](https://user-images.githubusercontent.com/21053648/43819845-f503562e-9b16-11e8-8a16-3d1698c77c54.png)
![code markdown 2](https://user-images.githubusercontent.com/21053648/43819847-f52e2bec-9b16-11e8-9f07-3d1c5b0adb22.png)

Every paragraph after the iframe (for all verticals) doesn't get parsed correctly and appears as a String instead of a ```<p>``` tag. The ```<p>``` tags that follow the first paragraph are parsed correctly as shown in the photo above with the text "If you're tired, go to sleep. Otherwise, stay awake."

**Comment by svarlamov** [comment]
Fixed in eocsutil via 31eb516d81efbc6fc612489e065cf49efb9fc44a - will re-parse courses into prod soon...
